### ISSUE TITLE
🟢  S1 - Protótipo

### ISSUE THREAD

**Issue by kabianca** [clasimplicio/SAP008-burger-queen-api-client#1]
- [x] Definir nome;
- [x] Cores;
- [x] Fontes;
- [x] As páginas;

#### Páginas:

- [x] Login;
- [x] Cadastro;
- [x] Cardápio;
- [x] Cozinha;
- [x] Pedido;

**Comment by kabianca** [comment]
Protótipo de baixa:

![Prototipo de baixa fidelidade](https://user-images.githubusercontent.com/101295603/197424630-31aebdf7-dc21-4274-9c4b-0a357bfcf823.jpg)

**Comment by kabianca** [comment]
Protótipo navegável para coleta de feedback, clique [aqui](https://www.figma.com/proto/Jl9eIgSnh2LOXIDddGF3t4/Untitled?node-id=1%3A2&scaling=scale-down&page-id=0%3A1&starting-point-node-id=1%3A2)

**Comment by clasimplicio** [comment]
massa. na hora do jantar vou pedir pros meus irmãos

**Comment by clasimplicio** [comment]
e ficou massa a tabelinha dos pedidos... valeu, karla
